name: "JiraSystem-Test"
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - run: |
          git log -n 3 --pretty=format:%s | grep "JIRA-" && echo "JIRA looks OK"
